env:
  browser: true
  es6: true
  jest: true
extends: 'eslint:recommended'
rules:
  indent:
    - off
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-cond-assign: [1, except-parens]
  no-const-assign: 1
  no-useless-escape: 0
globals:
  $: false
  jQuery: false
  hello: false
  Handlebars: true
  uuid: false
  XLSX: false
  XlsxPopulate: false
  saveAs: false
  showdown: false
  loki: false
  google: false
  gapi: false
  localforage: false
  ClipboardJS: false
  Hashes: false
  fetchJsonp: false
  moment: false
  dayjs: false
  autosize: false
  html2canvas: false
  jsPDF: false
  _: false
  Waves: false
  Mousetrap: false
  Hammer: false
  objectHash: false
  chrome: false
  chai: false
  chance: false
  underscoreDeepExtend: false
  quotedPrintable: false
  jsyaml: false
  d3: false
  DeepDiff: false
  GOOGLE_SCOPES: false
  GOOGLE_CLIENT_ID: false
  GOOGLE_KEY: false
  Google_API: true
  Github_API: true
  Interact: true
  Display: true
  App: true
  Flags: true
  Controller: true
  Css: true
  Dates: true
  Main: true
  Service: true
  Recent: true
  Table: true
  Datatable: true
  Folder: true
  Network: true
  Page: true
  Fields: true
  Forms: true
  Help: true
  Router: true
  Items: true
  Data: true
  Headers: true
  Config: true
  Query: true
  Saver: true
  Notify: true
  Strings: true
  Grid: true
  Scroll: true
  Filters: true
  ReadOnly: true
  ReadWrite: true
  Master: true
  Records: true
  Tasks: true
  Analysis: true
  Signatures: true
  Trackers: true
  Evidence: true
  Google_Sheets_Grid: true
  Google_Sheets_Metadata: true
  Google_Sheets_Notation: true
  Google_Sheets_Format: true
  Google_Sheets_Properties: true
  Dialog: true
  Example: true
  SaaD: true
  Credentials: true
  Events: true
  Link: true
  Schema: true
  Colours: true
  Sheets: true
  TeamDrives: true
  Groups: true
  Filter: true
  Database: true
  Task: true
  Archive: true
  Calendars: true
  Classes: true
  Errors: true
  Graphs: true
  Menu: true
  Views: true
  Decode: true
  Bookings: true
  Calendar: true
  Diary: true
  Manage: true
  Resources: true
  Source: true
  States: true
  Action: true
  Create: true
  Edit: true
  Elicit: true
  Export: true
  Files: true
  Helper: true
  Load: true
  Process: true
  Prompt: true
  Replacers: true
  Save: true
  Scales: true
  Show: true
  Hookup: true
  Render: true
  Url: true
  Access: true
  Log: true
  Populate: true
  Tracking: true
  Portfolio: true
  Update: true
  Exporter: true
  Tabulate: true
  Overview: true
  People: true
  Roster: true
  Usage: true
  iSAMS_API: true
  Templating: true
  Classwork: true
  
  # Reflect Forms and Scales
  __Ω__UK_Teachers_Standards: true
  __Σ__Evidence_Tracker: true
  __Σ__Form_Master: true
  __Σ__UK_Teachers_Reflective: true
  __Σ__Volunteering: true
  __Σ__Progress: true
  __Σ__UK_Teachers_Lesson_Observation: true
  __Σ__UK_Teachers_Grading: true