env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - off
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
globals:
  $: false
  jQuery: false
  hello: false
  Handlebars: false
  XLSX: false
  saveAs: false
  showdown: false
  loki: false
  google: false
  localforage: false
  ClipboardJS: false
  Hashes: false
  fetchJsonp: false
  moment: false
  autosize: false
  html2canvas: false
  jsPDF: false
  _: false
  Waves: false
  Mousetrap: false
  Hammer: false
  objectHash: false
  GOOGLE_SCOPES: false
  GOOGLE_CLIENT_ID: false
  GOOGLE_KEY: false
  Google_API: true
  Github_API: true
  global: true
  Interact: true
  Display: true
  App: true
  Flags: true
  Controller: true
  Css: true
  Main: true
  Service: true
  Recent: true
  Table: true
  Datatable: true
  Folder: true
  Network: true
  Page: true
  Fields: true
  Forms: true
  Help: true
  Router: true
  Items: true
  Data: true
  Headers: true
  Query: true
  Saver: true
  Strings: true
  Grid: true
  Scroll: true
  Filters: true
  ReadOnly: true
  ReadWrite: true
  Master: true
  Records: true
  Tasks: true
  Google_Sheets_Grid: true
  Google_Sheets_Metadata: true
  Google_Sheets_Notation: true
  Dialog: true
  Example: true
  Saad: true
  SaaD: true
  Credentials: true
  Events: true