# Global
safe:									true
exclude:							[TODO.md, REPOSITORY.md, CNAME, Gemfile, Gemfile.lock, __tests__]
include:							[_pages, _apps, _guides, _tutorials, _extensions, _tools, _others, _extras, _scripts]
timezone:							Europe/London

# Dependencies
markdown:							kramdown
  
# Styling
sass:
  sass_dir:						_sass
  load_paths:
                      - _sass
                      - _sass/bootstrap
                      - _sass/material
                      - _sass/custom
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  startings:					[]
  endings:            []
  artifacts:          [" /* */ ", " /* */", "/* */ ", "/* */", "/*jshint ignore:start*/", "/*jshint ignore:end*/"]
  ignore:
    envs:             [debug]

# Permalinks
permalink:						pretty

# Setup
title:								"EDUC.IO"
byline:								""

description:					"Web Apps & Tools built for Google Apps"
lead: 								"A collection of free web apps that integrate with the Google platform"
url:									https://educ.io
baseurl:							/
support:              "Get help, and support our work!"
repo:                 https://github.com/Educ-IO/educ-io.github.io
author:
  name:								"Educ.IO"
  url:								https://github.com/educ-io

# Collections
collections:
  articles:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  apps:
    output: true
  extensions:
    output: true
  tests:
    output: false

# Collection Defaults
defaults:
  - scope:
      path: ""
      type: tests
    values:
      sitemap:
        exclude: true
  
# Custom Variables
launched:							"2015"
debug:                "debug"
performance:          "perf"
compress:             "compress"
array:                []
highlight:            "af0ad9"
icon:                 "data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKDj+ADg/v8Aa9DxDlPK8TtCx/KWQ8fyskjI81Vr0/UFY9H0AAAAAAAAAAAAAAAAAAAAAAC16foA////AGLR9gxVyO4uR8bwcT3D77s9v+nhNsPx+jnE8vo4xPHQUMvzGVHL8wAAAAAAAAAAAAAAAAAAAAAAV830AFjN9BI+xvKmO8Hs5Tm/6/g3wu/8Pr3n/DvE8P08xfL7PsXy0VTM8xlUzPMAAAAAAAAAAAAAAAAAAAAAAE7K8wBNyvMbN8Px2Dq+6vk/vuf7PMTw+j/B6/FGwuvDQsfyg1HL80J82PYFc9X1AAAAAAAAAAAAAAAAAAAAAABjz/IAZdDzE0bC6sE/vuf8Qbvj9EvC6ZRHyfRIXszwFgBb/wCw3u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUszzAFLM8xg6xPHOOcTy+jjE8fZEx/FqLcDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPL8gBSy/MZO8Lu0j3A6vg8w+/5QMbyxkXI8oVLyfMys+j6AXTV9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjz/MAZtHzEkXD7L88vef8O77p/TfD8vs4xPH8OsTytGPQ9Ali0PQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATsvzAE3K8xs3xPLVOL/r+Dy95/s7xPH8PMXy/D7F8rli0PQKY9H0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFzN8gBczvMWQsLryD+85fpCueD2RcLqu0HH84hTzPM+n+L4An/Z9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABZzfMAW87zFT/E78Y6w/D8O8Lv9ErG72EAq+YAVs3zGlTM8yxj0PQITMrzAPL7/gAAAAAAAAAAAAAAAAAAAAAAT8vzAE7K8xs4w/DWO8Lu+DnD8fhCxvGlR8TsgzrE8tQ8xfLjP8byl1rO9A5YzfQAAAAAAAAAAAAAAAAAAAAAAGPP8gBm0fMSRsLrvz+85vw9wOv8OMLv+Tq96Po2w/H9OsXy+zfE8dpNyvMcTsrzAAAAAAAAAAAAAAAAAAAAAABRy/MAUcvzGTnE8tA4v+z5Or7q/TnD8PtAvuj8P8Pu+D3F8uRFyPKlX8/0El7P9AAAAAAAAAAAAAAAAAAAAAAAVMzzAFTM8xk9xfLQPMLu+kG/6PpAw+7hP8Tvuk/E63BQy/ItZdH1DP///wDQ8fwAAAAAAAAAAAAAAAAAAAAAAHLV9QB+2fYFT8vzVUDG8rFExfCVWsjsOmPT9w3f//8AlOj+AAAAAAAAAAAAAAAAAAAAAAAAAAAA/AcAAOAHAADgBwAA4AcAAOA/AADg/wAA4B8AAOAfAADgHwAA4B8AAOCPAADgBwAA4AcAAOAHAADgBwAA4D8AAA=="

# Extras
analytics:
  id:                 "UA-53673057-5"
  scroll:							true

app:
  alert:              info
  content:            content
  namespace:          educ
  tests:              _tests
  unsubscribe:        https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=TVU44HN7F5YE8
  check:
    url:              https://script.google.com/macros/s/AKfycbxSo9ufMpvyNVI9nkNDCOVI8E3xSbU7OHlfMhNIx8lJZ6zSY0Jo/exec