# Global
safe:									true
exclude:							[TODO.md, REPOSITORY.md, CNAME]
include:							[_pages, _apps, _extensions,_config]
timezone:							Europe/London

# Dependencies
markdown:							kramdown

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  endings:            all
  ignore:
    envs:             [debug]

# Permalinks
permalink:						pretty

# Setup
title:								"Educ.io"
byline:								""
  
description:					"Web Apps & Tools using Google Apps"
url:									https://educ.io
baseurl:							/
repo:                 https://github.com/Educ-IO/educ-io.github.io
author:
  name:								"Educ.io"
  url:								https://github.com/educ-io

# Custom variables
version:							"0.0.2"
launched:							"2015"
fonts:								"Cabin+Sketch:400,700"

# Extras
analytics:
  id:                 "UA-53673057-5"
  scroll:							true
  
api_keys:
  google_general:			"AIzaSyDB4zqDt8WB-DgimvEiCDrSvi8BTaZftxY"
  google_oauth:				"290943130848-2elj62n7h7hro65viq53cjddg3ln6i4a.apps.googleusercontent.com"

css:
  bootstrap:          "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"