# Global
safe:									true
exclude:							[README.md, LICENSE.md, TODO.md, CNAME]
include:							[_pages, _apps]
timezone:							Europe/London

# Dependencies
markdown:							kramdown

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all

# Permalinks
permalink:						pretty

# Setup
title:								"Educ.io"
byline:								""
  
description:					""
url:									educ.io
baseurl:							/
author:
  name:								"Educ.io"
  url:								https://github.com/educ-io

# Custom variables
version:							"0.0.1"
launched:							"2015"
fonts:								"Cabin+Sketch:400,700"
production:           false

# Extras
analytics:
  enable:							false
  id:                 "UA-53673057-5"
  
api_keys:
  google_general:			"AIzaSyDB4zqDt8WB-DgimvEiCDrSvi8BTaZftxY"
  google_oauth:				"290943130848-2elj62n7h7hro65viq53cjddg3ln6i4a.apps.googleusercontent.com"

css:
  bootstrap:          "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"