# Global
safe:									true
exclude:							[TODO.md, REPOSITORY.md, CNAME, Gemfile, Gemfile.lock]
include:							[__tests__, __puppeteer__, _pages, _apps, _guides, _extensions, _others, _extras, _scripts]
timezone:							Europe/London

# Dependencies
markdown:							kramdown

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  endings:            all
  artifacts:          ["/* */ ", "/* */", "/*jshint ignore:start*/", "/*jshint ignore:end*/"]
  ignore:
    envs:             [debug]

# Permalinks
permalink:						pretty

# Setup
title:								"Educ.io"
byline:								""
  
description:					"Web Apps & Tools built using Google Apps"
url:									https://educ.io
baseurl:							/
repo:                 https://github.com/Educ-IO/educ-io.github.io
author:
  name:								"Educ.io"
  url:								https://github.com/educ-io

# Custom variables
launched:							"2015"
debug:                "debug"
performance:          "perf"
compress:             "compress"
array:                []
highlight:            "#af0ad9"

# Extras
analytics:
  id:                 "UA-53673057-5"
  scroll:							true

app:
  content:            content
  namespace:          educ
  unsubscribe:        https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=TVU44HN7F5YE8
  check:
    url:              https://script.google.com/macros/s/AKfycbxSo9ufMpvyNVI9nkNDCOVI8E3xSbU7OHlfMhNIx8lJZ6zSY0Jo/exec