# Global
safe:									true
exclude:							[TODO.md, REPOSITORY.md, CNAME, Gemfile, Gemfile.lock, __tests__]
include:							[_pages, _apps, _guides, _tutorials, _extensions, _tools, _others, _extras, _scripts]
timezone:							Europe/London

# Dependencies
markdown:							kramdown
  
# Styling
sass:
  sass_dir:						_sass
  load_paths:
                      - _sass
                      - _sass/bootstrap
                      - _sass/material
                      - _sass/custom
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  endings:            all
  artifacts:          ["/* */ ", "/* */", "/*jshint ignore:start*/", "/*jshint ignore:end*/"]
  ignore:
    envs:             [debug]

# Permalinks
permalink:						pretty

# Setup
title:								"EDUC.IO"
byline:								""
  
description:					"Web Apps & Tools built for Google Apps"
lead: 								"A collection of free web apps that integrate with the Google platform"
url:									https://educ.io
baseurl:							/
support:              "Get help, and support our work!"
repo:                 https://github.com/Educ-IO/educ-io.github.io
author:
  name:								"Educ.IO"
  url:								https://github.com/educ-io

# Collections
collections:
  articles:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  apps:
    output: true
  extensions:
    output: true
  tests:
    output: false

# Collection Defaults
defaults:
  - scope:
      path: ""
      type: tests
    values:
      sitemap:
        exclude: true
  
# Custom Variables
launched:							"2015"
debug:                "debug"
performance:          "perf"
compress:             "compress"
array:                []
highlight:            "af0ad9"

# Extras
analytics:
  id:                 "UA-53673057-5"
  scroll:							true

app:
  content:            content
  namespace:          educ
  tests:              _tests
  unsubscribe:        https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=TVU44HN7F5YE8
  check:
    url:              https://script.google.com/macros/s/AKfycbxSo9ufMpvyNVI9nkNDCOVI8E3xSbU7OHlfMhNIx8lJZ6zSY0Jo/exec